### ISSUE TITLE
Cannot enable SSL for emqx-dashboard plugin.

### ISSUE THREAD

**Issue by kiranpradeep** [emqx/emqx-dashboard#136] opened 2019-08-14 11:57 UTC
Below are 6 steps to consistently reproduce the problem. I used certificates already part of emqx container.

1. docker pull emqx/emqx:v3.2.1 

2. docker image ls emqx/emqx:v3.2.1
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
emqx/emqx           v3.2.1              95b29971f356        3 weeks ago         87.6MB
```
3. docker run --rm -d --name emqx \
-e EMQX_LOADED_PLUGINS="emqx_management,emqx_recon,emqx_dashboard" \
-e EMQX_DASHBOARD__LISTENER__HTTPS=18084 \
-e EMQX_DASHBOARD__LISTENER__HTTPS__ACCEPTORS=2 \
-e EMQX_DASHBOARD__LISTENER__HTTPS__MAX_CLIENTS=512 \
-e EMQX_DASHBOARD__LISTENER__HTTPS__CACERTFILE="etc/certs/cacert.pem" \
-e EMQX_DASHBOARD__LISTENER__HTTPS__CERTFILE="etc/certs/cert.pem" \
-e EMQX_DASHBOARD__LISTENER__HTTPS__KEYFILE="etc/certs/key.pem" \
emqx/emqx:v3.2.1

4. docker ps -f name=emqx

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                                             NAMES
f9dcae3093d6        emqx/emqx:v3.2.1    "/usr/bin/docker-ent…"   6 minutes ago       Up 6 minutes        1883/tcp, 4369/tcp, 5369/tcp, 6369/tcp, 8080/tcp, 8083-8084/tcp, 8883/tcp, 11883/tcp, 18083/tcp   emqx
```
5. docker exec -it emqx /bin/sh
```
/opt/emqx $ ls -l etc/certs/*.pem
-rw-rw-r--    1 emqx     emqx          1021 Jul 20 12:16 etc/certs/cacert.pem
-rw-rw-r--    1 emqx     emqx          1070 Jul 20 12:16 etc/certs/cert.pem
-rw-rw-r--    1 emqx     emqx          1070 Jul 20 12:16 etc/certs/client-cert.pem
-rw-rw-r--    1 emqx     emqx          1675 Jul 20 12:16 etc/certs/client-key.pem
-rw-rw-r--    1 emqx     emqx          1675 Jul 20 12:16 etc/certs/key.pem
```

6. docker logs -f emqx

```
node.max_ports=1048576
dashboard.listener.https.max_clients=512
listener.tcp.external.acceptors=64
dashboard.listener.https.certfile=etc/certs/cert.pem
dashboard.listener.https=18084
listener.ssl.external.acceptors=32
node.process_limit=2097152
node.max_ets_tables=2097152
dashboard.listener.https.acceptors=2
dashboard.listener.https.keyfile=etc/certs/key.pem
listener.ws.external.acceptors=16
dashboard.listener.https.cacertfile=etc/certs/cacert.pem
node.name=f9dcae3093d6@172.17.0.4
EMQX_LOADED_PLUGINS=emqx_management,emqx_recon,emqx_dashboard
emqx v3.2.1 is started successfully!
2019-08-14 11:32:27.635 [error] Failed to start Ranch listener 'https:dashboard' in ranch_ssl:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{next_protocols_advertised,[<<"h2">>,<<"http/1.1">>]},{alpn_preferred_protocols,[<<"h2">>,<<"http/1.1">>]},{port,18084}]) for reason no_cert (no certificate provided; see cert, certfile, sni_fun or sni_hosts options)
2019-08-14 11:32:27.635 [error] supervisor: {<0.1615.0>,ranch_listener_sup}
    errorContext: start_error
    reason: {listen_error,'https:dashboard',no_cert}
    offender: [{pid,undefined},
               {id,ranch_acceptors_sup},
               {mfargs,
                   {ranch_acceptors_sup,start_link,
                       ['https:dashboard',ranch_ssl]}},
               {restart_type,permanent},
               {shutdown,infinity},
               {child_type,supervisor}]
2019-08-14 11:32:27.635 [error] crasher:
    initial call: supervisor:ranch_acceptors_sup/1
    pid: <0.1617.0>
    registered_name: []
    exception exit: {listen_error,'https:dashboard',no_cert}
      in function  ranch_acceptors_sup:listen_error/5 (/emqx_rel/_build/emqx/lib/ranch/src/ranch_acceptors_sup.erl, line 66)
      in call from ranch_acceptors_sup:init/1 (/emqx_rel/_build/emqx/lib/ranch/src/ranch_acceptors_sup.erl, line 44)
      in call from supervisor:init/1 (supervisor.erl, line 295)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [<0.1615.0>,ranch_sup,<0.1331.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1615.0>]
    dictionary: [{logger,error_logger}]
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 23115
  neighbours:
2019-08-14 11:32:27.636 [error] crasher:
    initial call: application_master:init/4
    pid: <0.1604.0>
    registered_name: []
    exception exit: {bad_return,
                     {{emqx_dashboard_app,start,[normal,[]]},
                      {'EXIT',
                       {{badmatch,{error,no_cert}},
                        [{minirest,start_https,3,
                          [{file,
                            "/emqx_rel/_build/emqx/lib/minirest/src/minirest.erl"},
                           {line,53}]},
                         {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
                         {emqx_dashboard_app,start,2,
                          [{file,
                            "/emqx_rel/_build/emqx/lib/emqx_dashboard/src/emqx_dashboard_app.erl"},
                           {line,28}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,277}]}]}}}}
      in function  application_master:init/4 (application_master.erl, line 138)
    ancestors: [<0.1603.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.1605.0>,normal}]
    links: [<0.1603.0>,<0.1253.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 242
  neighbours:
2019-08-14 11:32:27.637 [error] [Plugins] Load plugin emqx_dashboard failed, cannot start plugin emqx_dashboard for {bad_return,
                                                                                     {{emqx_dashboard_app,
                                                                                       start,
                                                                                       [normal,
                                                                                        []]},
                                                                                      {'EXIT',
                                                                                       {{badmatch,
                                                                                         {error,
                                                                                          no_cert}},
                                                                                        [{minirest,
                                                                                          start_https,
                                                                                          3,
                                                                                          [{file,
                                                                                            "/emqx_rel/_build/emqx/lib/minirest/src/minirest.erl"},
                                                                                           {line,
                                                                                            53}]},
                                                                                         {lists,
                                                                                          foreach,
                                                                                          2,
                                                                                          [{file,
                                                                                            "lists.erl"},
                                                                                           {line,
                                                                                            1338}]},
                                                                                         {emqx_dashboard_app,
                                                                                          start,
                                                                                          2,
                                                                                          [{file,
                                                                                            "/emqx_rel/_build/emqx/lib/emqx_dashboard/src/emqx_dashboard_app.erl"},
                                                                                           {line,
                                                                                            28}]},
                                                                                         {application_master,
                                                                                          start_it_old,
                                                                                          4,
                                                                                          [{file,
                                                                                            "application_master.erl"},
                                                                                           {line,
                                                                                            277}]}]}}}}
['2019-08-14T11:32:33Z']:emqx start

```

**Comment by dopry** [comment] 2019-09-05 19:57
I can reproduce with custom certs as well.

**Comment by dopry** [comment] 2019-09-05 20:35
I did some looking. In https://github.com/emqx/emqx-docker/blob/5a9933d3a0f73ab3593723ce4b8548e3bf6f594e/v3.2/docker-entrypoint.sh#L114 it looks like it is only applying values found in https://github.com/emqx/emqx/blob/master/etc/emqx.conf.

During the emqx move it seems like the dashboard configuration was removed from etc/emqx.conf

**Comment by zhanghongtong** [comment] 2019-09-06 07:59
@dopry Thank you for your feedback. This is a bug, we will fix it in the next release

**Comment by dopry** [comment] 2019-09-06 15:03
@zhanghongtong  thanks! It would be really nice to see this in a 3.x maintenance release, also.

**Comment by zhanghongtong** [comment] 2019-09-06 15:07
@dopry  In our plans, it will be fixed in the 4.0-bet.1 release

**Comment by turtleDeng** [comment] 2019-09-16 05:52
Sorry, thank you for your feedback, we have fixed it in v3.2.3.

**Comment by notjulian** [comment] 2019-09-17 08:29
> Thank you for your feedback, we have fixed it in v3.2.3.

hello
I've have the same error with 3.2.3

thanks

**Comment by turtleDeng** [comment] 2019-09-18 00:54
The port being monitored is duplicated. Please check if the port is correct.

**Comment by notjulian** [comment] 2019-09-18 06:08
> @notjulian The port being monitored is duplicated. Please check if the port is correct.

Hi,
this is the file config

```
##--------------------------------------------------------------------
## HTTP Listener

## The IP address and port that the Dashboard HTTP listener will bind.
##
## Value: Port
##
## Examples: 18083
dashboard.listener.http = 18085

## The acceptor pool for external Dashboard HTTP listener.
##
## Value: Number
dashboard.listener.http.acceptors = 4

## Maximum number of concurrent Dashboard HTTP connections.
##
## Value: Number
dashboard.listener.http.max_clients = 512
##--------------------------------------------------------------------
## HTTPS Listener

## The IP address and port that the Dashboard HTTPS listener will bind.
##
## Value: IP:Port | Port
##
## Examples: 18084, 127.0.0.1:18084, ::1:18084
dashboard.listener.https = 18086

## The acceptor pool for external Dashboard HTTPS listener.
##
## Value: Number
dashboard.listener.https.acceptors = 2

## Maximum number of concurrent Dashboard HTTPS connections.
##
## Value: Number
dashboard.listener.https.max_clients = 512

## Path to the file containing the user's private PEM-encoded key.
##
## Value: File
dashboard.listener.https.keyfile = /etc/emqx/certs/privkey1.pem
```

**Closed** 2019-10-19 13:40 UTC
Labels: bug

**Comment by kiranpradeep** [comment] 2019-10-19 13:41
The original issue is resolved in 3.2.3. I am not sure why this was opened later. Closing.

**Comment by ismailozturk07** [comment] 2019-11-01 23:13
@notjulian I have that same problem. dashboard does not open as https(18084). Did you reach the solution?

**Comment by notjulian** [comment] 2019-11-02 17:28
@ismailozturk07 
Hi, 
with latest version and the config above works flawlessly

post your config
and 
sudo netstat -nWvp | grep 18084
